language: objective-c
osx_image: xcode8.2
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=Example/Pyramid.xcodeproj
git:
  submodules: false
matrix:
    - env: JOB="XCODE" DEST="OS=9.3,name=iPhone 6" SCHEME="Pyramid-Example" SDK="iphonesimulator" ACTION="test"
script:
  - cd Example && pod install
  - set -o pipefail
  - open -b com.apple.iphonesimulator # Workaround https://github.com/travis-ci/travis-ci/issues/3040
  - xcodebuild "$ACTION" -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DEST" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
notifications:
  email:
    on_success: never
