language: objective-c
osx_image: xcode11
env:
  global:
    - LC_CTYPE=en_US.UTF-8
git:
  submodules: false
matrix:
  include:
    - env: JOB="POD_LINT"
      script: 
        - pod lib lint

    - env: JOB="XCODE" DEST="platform=iOS Simulator,OS=13.0,name=iPhone 8" SCHEME="Pyramid-Example" SDK="iphonesimulator" ACTION="test"
      script:
        - cd Example && pod update
        - set -o pipefail
        - xcodebuild "$ACTION" -workspace "Pyramid.xcworkspace" -scheme "$SCHEME" -sdk "$SDK" -destination "$DEST" -configuration Release ENABLE_TESTABILITY=YES | xcpretty
notifications:
  email:
    on_success: never
